name: ewb
favicon: null
layout_spectrum: 0.3620352945290506
typography_spectrum: 0.47057712893001735
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.7497385849710554
  lightness: 0.8623807746917009
  saturation: 0.2178888984490186
  rhythmicContrast: 0.5662443249020725
purpose: []
